name: ajacobsontv
favicon: null
layout_spectrum: 0.7522003932390362
typography_spectrum: 0.002803038340061903
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.23450442939065397
  lightness: 0.9657588531263173
  saturation: 0.1058269941713661
  rhythmicContrast: 0.9126993464305997
purpose: []
